ALTER FOREIGN TABLE 調査3術前情報 ADD COLUMN clinicalFrailtyScale int2;
ALTER FOREIGN TABLE 調査4術前情報 ADD COLUMN clinicalFrailtyScale int2;
ALTER FOREIGN TABLE 調査5術前情報 ADD COLUMN clinicalFrailtyScale int2;
ALTER FOREIGN TABLE 調査6術前情報 ADD COLUMN clinicalFrailtyScale int2;

ALTER FOREIGN TABLE 調査3患者背景 ADD COLUMN 外科的に留置した大動脈生体弁SAVの種類 int2;
ALTER FOREIGN TABLE 調査3患者背景 ADD COLUMN ステント付き生体弁の製品種別 int2;
ALTER FOREIGN TABLE 調査3患者背景 ADD COLUMN ステントレス同種移植ホモグラフトの別 int2;
ALTER FOREIGN TABLE 調査3患者背景 ADD COLUMN ステントレス生体弁の製品種別 int2;
ALTER FOREIGN TABLE 調査3患者背景 ADD COLUMN ステント付き生体弁の製品名その他 TEXT;
ALTER FOREIGN TABLE 調査3患者背景 ADD COLUMN ステントレス生体弁の製品名その他 TEXT;

ALTER FOREIGN TABLE 調査4患者背景 ADD COLUMN 外科的に留置した大動脈生体弁SAVの種類 int2;
ALTER FOREIGN TABLE 調査4患者背景 ADD COLUMN ステント付き生体弁の製品種別 int2;
ALTER FOREIGN TABLE 調査4患者背景 ADD COLUMN ステントレス同種移植ホモグラフトの別 int2;
ALTER FOREIGN TABLE 調査4患者背景 ADD COLUMN ステントレス生体弁の製品種別 int2;
ALTER FOREIGN TABLE 調査4患者背景 ADD COLUMN ステント付き生体弁の製品名その他 TEXT;
ALTER FOREIGN TABLE 調査4患者背景 ADD COLUMN ステントレス生体弁の製品名その他 TEXT;

ALTER FOREIGN TABLE 調査5患者背景 ADD COLUMN 外科的に留置した大動脈生体弁SAVの種類 int2;
ALTER FOREIGN TABLE 調査5患者背景 ADD COLUMN ステント付き生体弁の製品種別 int2;
ALTER FOREIGN TABLE 調査5患者背景 ADD COLUMN ステントレス同種移植ホモグラフトの別 int2;
ALTER FOREIGN TABLE 調査5患者背景 ADD COLUMN ステントレス生体弁の製品種別 int2;
ALTER FOREIGN TABLE 調査5患者背景 ADD COLUMN ステント付き生体弁の製品名その他 TEXT;
ALTER FOREIGN TABLE 調査5患者背景 ADD COLUMN ステントレス生体弁の製品名その他 TEXT;

ALTER FOREIGN TABLE 調査6患者背景 ADD COLUMN 外科的に留置した大動脈生体弁SAVの種類 int2;
ALTER FOREIGN TABLE 調査6患者背景 ADD COLUMN ステント付き生体弁の製品種別 int2;
ALTER FOREIGN TABLE 調査6患者背景 ADD COLUMN ステントレス同種移植ホモグラフトの別 int2;
ALTER FOREIGN TABLE 調査6患者背景 ADD COLUMN ステントレス生体弁の製品種別 int2;
ALTER FOREIGN TABLE 調査6患者背景 ADD COLUMN ステント付き生体弁の製品名その他 TEXT;
ALTER FOREIGN TABLE 調査6患者背景 ADD COLUMN ステントレス生体弁の製品名その他 TEXT;

ALTER FOREIGN TABLE 調査3術中情報 ADD COLUMN 製品_後拡張用バルーンカテーテル_製品名 TEXT;
ALTER FOREIGN TABLE 調査3術中情報 ADD COLUMN 製品_後拡張用バルーンカテーテル_サイズ int2;
ALTER FOREIGN TABLE 調査4術中情報 ADD COLUMN 製品_後拡張用バルーンカテーテル_製品名 TEXT;
ALTER FOREIGN TABLE 調査4術中情報 ADD COLUMN 製品_後拡張用バルーンカテーテル_サイズ int2;
ALTER FOREIGN TABLE 調査5術中情報 ADD COLUMN 製品_後拡張用バルーンカテーテル_製品名 TEXT;
ALTER FOREIGN TABLE 調査5術中情報 ADD COLUMN 製品_後拡張用バルーンカテーテル_サイズ int2;
ALTER FOREIGN TABLE 調査6術中情報 ADD COLUMN 製品_後拡張用バルーンカテーテル_製品名 TEXT;
ALTER FOREIGN TABLE 調査6術中情報 ADD COLUMN 製品_後拡張用バルーンカテーテル_サイズ int2;

ALTER FOREIGN TABLE 施設調査契約マスタ
    ADD 調査7契約有りフラグ BOOLEAN DEFAULT false NOT NULL,
    ADD 調査7登録症例件数 INTEGER;


ALTER FOREIGN TABLE 調査3tavi症例データ管理 ADD COLUMN 調査対象指定フラグ BOOLEAN NOT NULL DEFAULT(false);
ALTER FOREIGN TABLE 調査4tavi症例データ管理 ADD COLUMN 調査対象指定フラグ BOOLEAN NOT NULL DEFAULT(false);
ALTER FOREIGN TABLE 調査5tavi症例データ管理 ADD COLUMN 調査対象指定フラグ BOOLEAN NOT NULL DEFAULT(false);
ALTER FOREIGN TABLE 調査6tavi症例データ管理 ADD COLUMN 調査対象指定フラグ BOOLEAN NOT NULL DEFAULT(false);

-- ------------------------------------------------------------------------------------------
-- 調査7の外部テーブル作成
-- ------------------------------------------------------------------------------------------

-- リモートサーバ登録
CREATE SERVER tavi_investigation7_server FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host '127.0.0.1', port '5432', dbname 'tavi_investigation7');
-- ユーザマッピング
CREATE USER MAPPING FOR tavi_db_maker2 SERVER tavi_investigation7_server OPTIONS (user 'tavi_db_maker2', password 'tavitavi');

-- 外部テーブル作成1
DROP FOREIGN TABLE IF EXISTS 調査7tavi症例データ管理;
CREATE FOREIGN TABLE 調査7tavi症例データ管理 (
    id integer NOT NULL,
    tavi_registry_no character varying(8) NOT NULL,
    ncd_id text,
    施設マスタレコードid integer,
    院内管理コード character varying(50),
    前回のtavi_registry_no character varying(8),
    症例作業ステータス smallint NOT NULL DEFAULT 0,
    入力承認ステータス smallint NOT NULL DEFAULT 0,
    保存済フラグ_患者情報 boolean NOT NULL DEFAULT false,
    保存済フラグ_術前情報 boolean NOT NULL DEFAULT false,
    保存済フラグ_術中情報 boolean NOT NULL DEFAULT false,
    保存済フラグ_術後情報 boolean NOT NULL DEFAULT false,
    作業ステータス_フォローアップ7日後 smallint NOT NULL DEFAULT 0,
    作業ステータス_フォローアップ30日後 smallint NOT NULL DEFAULT 0,
    作業ステータス_フォローアップ6ヶ月後 smallint NOT NULL DEFAULT 0,
    作業ステータス_フォローアップ1年後 smallint NOT NULL DEFAULT 0,
    作業ステータス_フォローアップ2年後 smallint NOT NULL DEFAULT 0,
    作業ステータス_フォローアップ3年後 smallint NOT NULL DEFAULT 0,
    作業ステータス_フォローアップ4年後 smallint NOT NULL DEFAULT 0,
    作業ステータス_フォローアップ5年後 smallint NOT NULL DEFAULT 0,
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    連携済みフラグ boolean NOT NULL DEFAULT false,
    case_seq text,
    最終連携者id character varying(20),
    最終連携日時 timestamp without time zone,
    基本情報承認日時 timestamp without time zone,
    基本情報承認者id character varying(20),
    フォローアップ7日後承認日時 timestamp without time zone,
    フォローアップ7日後承認者id character varying(20),
    フォローアップ30日後承認日時 timestamp without time zone,
    フォローアップ30日後承認者id character varying(20),
    フォローアップ6ヶ月後承認日時 timestamp without time zone,
    フォローアップ6ヶ月後承認者id character varying(20),
    フォローアップ1年後承認日時 timestamp without time zone,
    フォローアップ1年後承認者id character varying(20),
    フォローアップ2年後承認日時 timestamp without time zone,
    フォローアップ2年後承認者id character varying(20),
    フォローアップ3年後承認日時 timestamp without time zone,
    フォローアップ3年後承認者id character varying(20),
    フォローアップ4年後承認日時 timestamp without time zone,
    フォローアップ4年後承認者id character varying(20),
    フォローアップ5年後承認日時 timestamp without time zone,
    フォローアップ5年後承認者id character varying(20),
    ncd施設診療科id text NOT NULL,
    症例データ区分 smallint NOT NULL DEFAULT 0,
    調査区分コード character varying(2),
    調査対象フラグ boolean NOT NULL DEFAULT false,
    調査対象フラグ更新日時 timestamp without time zone,
    調査完了日経過フラグ boolean NOT NULL DEFAULT false,
    調査対象指定フラグ boolean NOT NULL DEFAULT(false)
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'tavi症例データ管理');
ALTER FOREIGN TABLE public.調査7tavi症例データ管理 OWNER TO tavi_db_maker2;

-- 外部テーブル作成2
DROP FOREIGN TABLE IF EXISTS 調査7tavi症例承認時データ;
CREATE FOREIGN TABLE 調査7tavi症例承認時データ (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    症例テーブルマスタレコードid integer NOT NULL,
    比較対象レコードid integer NOT NULL,
    比較対象登録通番 smallint,
    差分出力日時 timestamp without time zone,
    症例更新者id character varying(20) NOT NULL,
    症例更新日時 timestamp without time zone NOT NULL,
    ncd_id text,
    院内管理コード character varying(50),
    前回のtavi_registry_no character varying(8)
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'tavi症例承認時データ');
ALTER FOREIGN TABLE public.調査7tavi症例承認時データ OWNER TO tavi_db_maker2;

-- 外部テーブル作成3
DROP FOREIGN TABLE IF EXISTS 調査7tavi症例承認時データ差分;
CREATE FOREIGN TABLE 調査7tavi症例承認時データ差分 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    症例入力項目マスタレコードid integer NOT NULL,
    更新前値 text,
    更新後値 text,
    オプション記録1 text,
    オプション記録2 text,
    オプション記録3 text,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    症例更新者id character varying(20) NOT NULL,
    症例更新日時 timestamp without time zone NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    バッチid character varying(50) NOT NULL,
    更新前tavi症例承認時データレコードid integer,
    更新後tavi症例承認時データレコードid integer,
    テーブル名 text,
    項目名 text
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'tavi症例承認時データ差分');
ALTER FOREIGN TABLE public.調査7tavi症例承認時データ差分 OWNER TO tavi_db_maker2;

-- 外部テーブル作成4
DROP FOREIGN TABLE IF EXISTS 調査7フォローアップ中有害事象;
CREATE FOREIGN TABLE 調査7フォローアップ中有害事象 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    有害事象登録通番 smallint NOT NULL,
    確認日_年 smallint,
    確認日_月 smallint,
    確認日_日 smallint,
    発現日_発生日_年 smallint,
    発現日_発生日_月 smallint,
    発現日_発生日_日 smallint,
    デバイスとの因果関係コード smallint NOT NULL DEFAULT (-1),
    手技との因果関係コード smallint NOT NULL DEFAULT (-1),
    重篤度コード smallint NOT NULL DEFAULT (-1),
    重篤と判断した理由コード smallint NOT NULL DEFAULT (-1),
    転帰コード smallint NOT NULL DEFAULT (-1),
    転帰その他詳細 text,
    転帰日_年 smallint,
    転帰日_月 smallint,
    転帰日_日 smallint,
    コメント text,
    デバイス関連有害事象有無 smallint NOT NULL DEFAULT (-1),
    出血関連有害事象有無 smallint NOT NULL DEFAULT (-1),
    循環器関連有害事象有無 smallint NOT NULL DEFAULT (-1),
    入院を要したその他有害事象有無 smallint NOT NULL DEFAULT (-1),
    有害事象カテゴリー smallint NOT NULL DEFAULT (-1),
    有害事象内容コード smallint NOT NULL DEFAULT (-1),
    入力された有害事象名 text,
    登録取消フラグ boolean NOT NULL DEFAULT false,
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT (-1),
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    入力承認ステータス smallint NOT NULL DEFAULT 0,
    有害事象名_デバイス関連その他 text,
    有害事象名_出血関連その他 text,
    有害事象名_入院_循環器系疾患 text,
    有害事象名_入院_消化器系疾患 text,
    有害事象名_入院_呼吸器系疾患 text,
    有害事象名_入院_神経系疾患 text,
    有害事象名_入院_その他腎臓系疾患 text,
    有害事象名_入院_感染性疾患 text,
    有害事象名_入院_その他 text
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'フォローアップ中有害事象');
ALTER FOREIGN TABLE public.調査7フォローアップ中有害事象 OWNER TO tavi_db_maker2;

-- 外部テーブル作成5
DROP FOREIGN TABLE IF EXISTS 調査7フォローアップ術後1年;
CREATE FOREIGN TABLE 調査7フォローアップ術後1年 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    退院日_年 smallint,
    退院日_月 smallint,
    退院日_日 smallint,
    検査実施日_年 smallint,
    検査実施日_月 smallint,
    検査実施日_日 smallint,
    生存確認コード smallint NOT NULL DEFAULT (-1),
    死亡_不明の経緯詳細 text,
    死亡日_年 smallint,
    死亡日_月 smallint,
    死亡日_日 smallint,
    死因コード smallint NOT NULL DEFAULT (-1),
    死因その他内容 text,
    死亡とデバイスとの因果関係 smallint NOT NULL DEFAULT (-1),
    死亡と手技との因果関係有無 smallint NOT NULL DEFAULT (-1),
    死亡に関するコメント text,
    classification_nyha smallint NOT NULL DEFAULT (-1),
    心エコー有無 smallint NOT NULL,
    心エコー_実施日_年 smallint,
    心エコー_実施日_月 smallint,
    心エコー_実施日_日 smallint,
    lvef smallint,
    大動脈弁逆流コード smallint NOT NULL DEFAULT (-1),
    逆流の箇所コード smallint NOT NULL DEFAULT (-1),
    大動脈弁圧較差 numeric(4,1),
    有効弁口面積 numeric(3,2),
    投与薬_アスピリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_チクロピジン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_クロピドグレル等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ワーファリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_直接トロンビン阻害薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬品名 text,
    投与薬_ace_inhibitors等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ベータ遮断薬有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合発生有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容コード smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容その他 text,
    デバイスの不具合による有害事象の発生有無 smallint NOT NULL DEFAULT (-1),
    デバイスの不具合発生状況の詳細 text,
    有害事象の有無 smallint NOT NULL DEFAULT (-1),
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    デバイスの不具合内容フラグ_ゆがみ boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_破損 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_移動 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_その他 boolean NOT NULL DEFAULT false
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'フォローアップ術後1年');
ALTER FOREIGN TABLE public.調査7フォローアップ術後1年 OWNER TO tavi_db_maker2;

-- 外部テーブル作成6
DROP FOREIGN TABLE IF EXISTS 調査7フォローアップ術後2年;
CREATE FOREIGN TABLE 調査7フォローアップ術後2年 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    退院日_年 smallint,
    退院日_月 smallint,
    退院日_日 smallint,
    検査実施日_年 smallint,
    検査実施日_月 smallint,
    検査実施日_日 smallint,
    生存確認コード smallint NOT NULL DEFAULT (-1),
    死亡_不明の経緯詳細 text,
    死亡日_年 smallint,
    死亡日_月 smallint,
    死亡日_日 smallint,
    死因コード smallint NOT NULL DEFAULT (-1),
    死因その他内容 text,
    死亡とデバイスとの因果関係 smallint NOT NULL DEFAULT (-1),
    死亡と手技との因果関係有無 smallint NOT NULL DEFAULT (-1),
    死亡に関するコメント text,
    classification_nyha smallint NOT NULL DEFAULT (-1),
    心エコー有無 smallint NOT NULL,
    心エコー_実施日_年 smallint,
    心エコー_実施日_月 smallint,
    心エコー_実施日_日 smallint,
    lvef smallint,
    大動脈弁逆流コード smallint NOT NULL DEFAULT (-1),
    逆流の箇所コード smallint NOT NULL DEFAULT (-1),
    大動脈弁圧較差 numeric(4,1),
    有効弁口面積 numeric(3,2),
    投与薬_アスピリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_チクロピジン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_クロピドグレル等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ワーファリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_直接トロンビン阻害薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬品名 text,
    投与薬_ace_inhibitors等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ベータ遮断薬有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合発生有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容コード smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容その他 text,
    デバイスの不具合による有害事象の発生有無 smallint NOT NULL DEFAULT (-1),
    デバイスの不具合発生状況の詳細 text,
    有害事象の有無 smallint NOT NULL DEFAULT (-1),
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    デバイスの不具合内容フラグ_ゆがみ boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_破損 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_移動 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_その他 boolean NOT NULL DEFAULT false
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'フォローアップ術後2年');
ALTER FOREIGN TABLE public.調査7フォローアップ術後2年 OWNER TO tavi_db_maker2;

-- 外部テーブル作成7
DROP FOREIGN TABLE IF EXISTS 調査7フォローアップ術後30日;
CREATE FOREIGN TABLE 調査7フォローアップ術後30日 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    退院日_年 smallint,
    退院日_月 smallint,
    退院日_日 smallint,
    検査実施日_年 smallint,
    検査実施日_月 smallint,
    検査実施日_日 smallint,
    生存確認コード smallint NOT NULL DEFAULT (-1),
    死亡_不明の経緯詳細 text,
    死亡日_年 smallint,
    死亡日_月 smallint,
    死亡日_日 smallint,
    死因コード smallint NOT NULL DEFAULT (-1),
    死因その他内容 text,
    死亡とデバイスとの因果関係 smallint NOT NULL DEFAULT (-1),
    死亡と手技との因果関係有無 smallint NOT NULL DEFAULT (-1),
    死亡に関するコメント text,
    classification_nyha smallint NOT NULL DEFAULT (-1),
    心エコー有無 smallint NOT NULL,
    心エコー_実施日_年 smallint,
    心エコー_実施日_月 smallint,
    心エコー_実施日_日 smallint,
    lvef smallint,
    大動脈弁逆流コード smallint NOT NULL DEFAULT (-1),
    逆流の箇所コード smallint NOT NULL DEFAULT (-1),
    大動脈弁圧較差 numeric(4,1),
    有効弁口面積 numeric(3,2),
    投与薬_アスピリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_チクロピジン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_クロピドグレル等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ワーファリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_直接トロンビン阻害薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬品名 text,
    投与薬_ace_inhibitors等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ベータ遮断薬有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合発生有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容コード smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容その他 text,
    デバイスの不具合による有害事象の発生有無 smallint NOT NULL DEFAULT (-1),
    デバイスの不具合発生状況の詳細 text,
    有害事象の有無 smallint NOT NULL DEFAULT (-1),
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    デバイスの不具合内容フラグ_ゆがみ boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_破損 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_移動 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_その他 boolean NOT NULL DEFAULT false
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'フォローアップ術後30日');
ALTER FOREIGN TABLE public.調査7フォローアップ術後30日 OWNER TO tavi_db_maker2;

-- 外部テーブル作成8
DROP FOREIGN TABLE IF EXISTS 調査7フォローアップ術後3年;
CREATE FOREIGN TABLE 調査7フォローアップ術後3年 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    退院日_年 smallint,
    退院日_月 smallint,
    退院日_日 smallint,
    検査実施日_年 smallint,
    検査実施日_月 smallint,
    検査実施日_日 smallint,
    生存確認コード smallint NOT NULL DEFAULT (-1),
    死亡_不明の経緯詳細 text,
    死亡日_年 smallint,
    死亡日_月 smallint,
    死亡日_日 smallint,
    死因コード smallint NOT NULL DEFAULT (-1),
    死因その他内容 text,
    死亡とデバイスとの因果関係 smallint NOT NULL DEFAULT (-1),
    死亡と手技との因果関係有無 smallint NOT NULL DEFAULT (-1),
    死亡に関するコメント text,
    classification_nyha smallint NOT NULL DEFAULT (-1),
    心エコー有無 smallint NOT NULL,
    心エコー_実施日_年 smallint,
    心エコー_実施日_月 smallint,
    心エコー_実施日_日 smallint,
    lvef smallint,
    大動脈弁逆流コード smallint NOT NULL DEFAULT (-1),
    逆流の箇所コード smallint NOT NULL DEFAULT (-1),
    大動脈弁圧較差 numeric(4,1),
    有効弁口面積 numeric(3,2),
    投与薬_アスピリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_チクロピジン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_クロピドグレル等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ワーファリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_直接トロンビン阻害薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬品名 text,
    投与薬_ace_inhibitors等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ベータ遮断薬有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合発生有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容コード smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容その他 text,
    デバイスの不具合による有害事象の発生有無 smallint NOT NULL DEFAULT (-1),
    デバイスの不具合発生状況の詳細 text,
    有害事象の有無 smallint NOT NULL DEFAULT (-1),
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    デバイスの不具合内容フラグ_ゆがみ boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_破損 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_移動 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_その他 boolean NOT NULL DEFAULT false
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'フォローアップ術後3年');
ALTER FOREIGN TABLE public.調査7フォローアップ術後3年 OWNER TO tavi_db_maker2;

-- 外部テーブル作成9
DROP FOREIGN TABLE IF EXISTS 調査7フォローアップ術後4年;
CREATE FOREIGN TABLE 調査7フォローアップ術後4年 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    退院日_年 smallint,
    退院日_月 smallint,
    退院日_日 smallint,
    検査実施日_年 smallint,
    検査実施日_月 smallint,
    検査実施日_日 smallint,
    生存確認コード smallint NOT NULL DEFAULT (-1),
    死亡_不明の経緯詳細 text,
    死亡日_年 smallint,
    死亡日_月 smallint,
    死亡日_日 smallint,
    死因コード smallint NOT NULL DEFAULT (-1),
    死因その他内容 text,
    死亡とデバイスとの因果関係 smallint NOT NULL DEFAULT (-1),
    死亡と手技との因果関係有無 smallint NOT NULL DEFAULT (-1),
    死亡に関するコメント text,
    classification_nyha smallint NOT NULL DEFAULT (-1),
    心エコー有無 smallint NOT NULL,
    心エコー_実施日_年 smallint,
    心エコー_実施日_月 smallint,
    心エコー_実施日_日 smallint,
    lvef smallint,
    大動脈弁逆流コード smallint NOT NULL DEFAULT (-1),
    逆流の箇所コード smallint NOT NULL DEFAULT (-1),
    大動脈弁圧較差 numeric(4,1),
    有効弁口面積 numeric(3,2),
    投与薬_アスピリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_チクロピジン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_クロピドグレル等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ワーファリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_直接トロンビン阻害薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬品名 text,
    投与薬_ace_inhibitors等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ベータ遮断薬有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合発生有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容コード smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容その他 text,
    デバイスの不具合による有害事象の発生有無 smallint NOT NULL DEFAULT (-1),
    デバイスの不具合発生状況の詳細 text,
    有害事象の有無 smallint NOT NULL DEFAULT (-1),
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    デバイスの不具合内容フラグ_ゆがみ boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_破損 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_移動 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_その他 boolean NOT NULL DEFAULT false
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'フォローアップ術後4年');
ALTER FOREIGN TABLE public.調査7フォローアップ術後4年 OWNER TO tavi_db_maker2;

-- 外部テーブル作成10
DROP FOREIGN TABLE IF EXISTS 調査7フォローアップ術後5年;
CREATE FOREIGN TABLE 調査7フォローアップ術後5年 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    退院日_年 smallint,
    退院日_月 smallint,
    退院日_日 smallint,
    検査実施日_年 smallint,
    検査実施日_月 smallint,
    検査実施日_日 smallint,
    生存確認コード smallint NOT NULL DEFAULT (-1),
    死亡_不明の経緯詳細 text,
    死亡日_年 smallint,
    死亡日_月 smallint,
    死亡日_日 smallint,
    死因コード smallint NOT NULL DEFAULT (-1),
    死因その他内容 text,
    死亡とデバイスとの因果関係 smallint NOT NULL DEFAULT (-1),
    死亡と手技との因果関係有無 smallint NOT NULL DEFAULT (-1),
    死亡に関するコメント text,
    classification_nyha smallint NOT NULL DEFAULT (-1),
    心エコー有無 smallint NOT NULL,
    心エコー_実施日_年 smallint,
    心エコー_実施日_月 smallint,
    心エコー_実施日_日 smallint,
    lvef smallint,
    大動脈弁逆流コード smallint NOT NULL DEFAULT (-1),
    逆流の箇所コード smallint NOT NULL DEFAULT (-1),
    大動脈弁圧較差 numeric(4,1),
    有効弁口面積 numeric(3,2),
    投与薬_アスピリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_チクロピジン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_クロピドグレル等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ワーファリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_直接トロンビン阻害薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬品名 text,
    投与薬_ace_inhibitors等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ベータ遮断薬有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合発生有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容コード smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容その他 text,
    デバイスの不具合による有害事象の発生有無 smallint NOT NULL DEFAULT (-1),
    デバイスの不具合発生状況の詳細 text,
    有害事象の有無 smallint NOT NULL DEFAULT (-1),
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    デバイスの不具合内容フラグ_ゆがみ boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_破損 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_移動 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_その他 boolean NOT NULL DEFAULT false
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'フォローアップ術後5年');
ALTER FOREIGN TABLE public.調査7フォローアップ術後5年 OWNER TO tavi_db_maker2;

-- 外部テーブル作成11
DROP FOREIGN TABLE IF EXISTS 調査7フォローアップ術後6ヶ月;
CREATE FOREIGN TABLE 調査7フォローアップ術後6ヶ月 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    退院日_年 smallint,
    退院日_月 smallint,
    退院日_日 smallint,
    検査実施日_年 smallint,
    検査実施日_月 smallint,
    検査実施日_日 smallint,
    生存確認コード smallint NOT NULL DEFAULT (-1),
    死亡_不明の経緯詳細 text,
    死亡日_年 smallint,
    死亡日_月 smallint,
    死亡日_日 smallint,
    死因コード smallint NOT NULL DEFAULT (-1),
    死因その他内容 text,
    死亡とデバイスとの因果関係 smallint NOT NULL DEFAULT (-1),
    死亡と手技との因果関係有無 smallint NOT NULL DEFAULT (-1),
    死亡に関するコメント text,
    classification_nyha smallint NOT NULL DEFAULT (-1),
    心エコー有無 smallint NOT NULL,
    心エコー_実施日_年 smallint,
    心エコー_実施日_月 smallint,
    心エコー_実施日_日 smallint,
    lvef smallint,
    大動脈弁逆流コード smallint NOT NULL DEFAULT (-1),
    逆流の箇所コード smallint NOT NULL DEFAULT (-1),
    大動脈弁圧較差 numeric(4,1),
    有効弁口面積 numeric(3,2),
    投与薬_アスピリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_チクロピジン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_クロピドグレル等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ワーファリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_直接トロンビン阻害薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬品名 text,
    投与薬_ace_inhibitors等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ベータ遮断薬有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合発生有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容コード smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容その他 text,
    デバイスの不具合による有害事象の発生有無 smallint NOT NULL DEFAULT (-1),
    デバイスの不具合発生状況の詳細 text,
    有害事象の有無 smallint NOT NULL DEFAULT (-1),
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    デバイスの不具合内容フラグ_ゆがみ boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_破損 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_移動 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_その他 boolean NOT NULL DEFAULT false
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'フォローアップ術後6ヶ月');
ALTER FOREIGN TABLE public.調査7フォローアップ術後6ヶ月 OWNER TO tavi_db_maker2;

-- 外部テーブル作成12
DROP FOREIGN TABLE IF EXISTS 調査7フォローアップ退院_術後7日;
CREATE FOREIGN TABLE 調査7フォローアップ退院_術後7日 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    退院日_年 smallint,
    退院日_月 smallint,
    退院日_日 smallint,
    検査実施日_年 smallint,
    検査実施日_月 smallint,
    検査実施日_日 smallint,
    生存確認コード smallint NOT NULL DEFAULT (-1),
    死亡_不明の経緯詳細 text,
    死亡日_年 smallint,
    死亡日_月 smallint,
    死亡日_日 smallint,
    死因コード smallint NOT NULL DEFAULT (-1),
    死因その他内容 text,
    死亡とデバイスとの因果関係 smallint NOT NULL DEFAULT (-1),
    死亡と手技との因果関係有無 smallint NOT NULL DEFAULT (-1),
    死亡に関するコメント text,
    classification_nyha smallint NOT NULL DEFAULT (-1),
    心エコー有無 smallint NOT NULL,
    心エコー_実施日_年 smallint,
    心エコー_実施日_月 smallint,
    心エコー_実施日_日 smallint,
    lvef smallint,
    大動脈弁逆流コード smallint NOT NULL DEFAULT (-1),
    逆流の箇所コード smallint NOT NULL DEFAULT (-1),
    大動脈弁圧較差 numeric(4,1),
    有効弁口面積 numeric(3,2),
    投与薬_アスピリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_チクロピジン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_クロピドグレル等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ワーファリン有無 smallint NOT NULL DEFAULT (-1),
    投与薬_直接トロンビン阻害薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_その他抗凝固薬品名 text,
    投与薬_ace_inhibitors等有無 smallint NOT NULL DEFAULT (-1),
    投与薬_ベータ遮断薬有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合発生有無 smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容コード smallint NOT NULL DEFAULT (-1),
    デバイス_tavi弁_の不具合内容その他 text,
    デバイスの不具合による有害事象の発生有無 smallint NOT NULL DEFAULT (-1),
    デバイスの不具合発生状況の詳細 text,
    有害事象の有無 smallint NOT NULL DEFAULT (-1),
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    デバイスの不具合内容フラグ_ゆがみ boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_破損 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_移動 boolean NOT NULL DEFAULT false,
    デバイスの不具合内容フラグ_その他 boolean NOT NULL DEFAULT false
)
SERVER tavi_investigation7_server
OPTIONS (table_name 'フォローアップ退院_術後7日');
ALTER FOREIGN TABLE public.調査7フォローアップ退院_術後7日 OWNER TO tavi_db_maker2;

-- 外部テーブル作成13
DROP FOREIGN TABLE IF EXISTS 調査7患者背景;
CREATE FOREIGN TABLE 調査7患者背景 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    患者イニシャル_前 character varying(1),
    患者イニシャル_後 character varying(1),
    患者生年月日_年 smallint,
    患者生年月日_月 smallint,
    患者生年月日_日 smallint,
    患者性別コード smallint NOT NULL DEFAULT (-1),
    人種フラグ_日本人 boolean NOT NULL DEFAULT false,
    人種フラグ_日本人以外のアジア系 boolean NOT NULL DEFAULT false,
    人種フラグ_白人系 boolean NOT NULL DEFAULT false,
    人種フラグ_アフリカ系 boolean NOT NULL DEFAULT false,
    人種フラグ_ヒスパニック系 boolean NOT NULL DEFAULT false,
    人種フラグ_太平洋諸島系 boolean NOT NULL DEFAULT false,
    身長 smallint,
    体重 smallint,
    喫煙歴有無 smallint NOT NULL DEFAULT (-1),
    糖尿病有無 smallint NOT NULL DEFAULT (-1),
    糖尿病治療有無 smallint NOT NULL DEFAULT (-1),
    糖尿病治療フラグ_食事療法 boolean NOT NULL DEFAULT false,
    糖尿病治療フラグ_薬物療法 boolean NOT NULL DEFAULT false,
    糖尿病治療フラグ_glp1注射 boolean NOT NULL DEFAULT false,
    糖尿病治療フラグ_インスリン boolean NOT NULL DEFAULT false,
    糖尿病治療フラグ_その他 boolean NOT NULL DEFAULT false,
    脂質異常症の既往有無 smallint NOT NULL DEFAULT (-1),
    慢性透析有無 smallint NOT NULL DEFAULT (-1),
    高血圧の既往有無 smallint NOT NULL DEFAULT (-1),
    感染性心内膜炎ieの既往有無 smallint NOT NULL DEFAULT (-1),
    ie_type smallint NOT NULL DEFAULT (-1),
    慢性呼吸障害コード smallint NOT NULL DEFAULT (-1),
    心臓外の血管病変有無 smallint NOT NULL DEFAULT (-1),
    心臓外の血管病変フラグ_胸部大動脈 boolean NOT NULL DEFAULT false,
    心臓外の血管病変フラグ_末梢血管 boolean NOT NULL DEFAULT false,
    脳障害の既往有無 smallint,
    脳障害の既往フラグ_tia boolean NOT NULL DEFAULT false,
    脳障害の既往フラグ_cva boolean NOT NULL DEFAULT false,
    脳障害_診断日_年 smallint,
    脳障害_診断日_月 smallint,
    脳障害_診断日_日 smallint,
    頸動脈病変の既往コード smallint NOT NULL DEFAULT (-1),
    頸動脈狭窄症_該当部位への施行有無 smallint NOT NULL DEFAULT (-1),
    開胸が困難な胸郭異常有無 smallint NOT NULL DEFAULT (-1),
    悪性腫瘍有無 smallint NOT NULL DEFAULT (-1),
    免疫不全有無 smallint NOT NULL DEFAULT (-1),
    非心臓血管系その他有無 smallint NOT NULL DEFAULT (-1),
    非心臓血管系その他詳細 text,
    以前の心臓手術の既往有無 smallint NOT NULL DEFAULT (-1),
    以前の手術名_cabg有無 smallint NOT NULL DEFAULT (-1),
    cabg_実施日_年 smallint,
    cabg_実施日_月 smallint,
    cabg_実施日_日 smallint,
    以前の手術名_valve有無 smallint NOT NULL DEFAULT (-1),
    以前の手術名_aorticvalve有無 smallint NOT NULL DEFAULT (-1),
    以前の手術名_avr有無 smallint NOT NULL DEFAULT (-1),
    avr_弁の種類コード smallint NOT NULL DEFAULT (-1),
    avr_実施日_年 smallint,
    avr_実施日_月 smallint,
    avr_実施日_日 smallint,
    以前の手術名_バルーン大動脈弁形成術有無 smallint NOT NULL DEFAULT (-1),
    以前の手術名_僧帽弁置換術有無 smallint NOT NULL DEFAULT (-1),
    僧帽弁置換術_弁の種類 smallint,
    以前の手術名_僧帽弁形成術有無 smallint NOT NULL DEFAULT (-1),
    以前の手術名_aortic有無 smallint NOT NULL DEFAULT (-1),
    以前の手術名_congenital有無 smallint NOT NULL DEFAULT (-1),
    以前の手術名_othercardiac有無 smallint NOT NULL DEFAULT (-1),
    以前の手術名_othercardiac回数 smallint NOT NULL DEFAULT (-1),
    以前の手術_other_cardiac_1回目の詳細 text,
    以前の手術_other_cardiac_2回目の詳細 text,
    以前の手術_other_cardiac_3回目の詳細 text,
    以前の手術_other_cardiac_4回目の詳細 text,
    previouspci有無 smallint NOT NULL DEFAULT (-1),
    previouspci実施日_年 smallint,
    previouspci実施日_月 smallint,
    previouspci実施日_日 smallint,
    pcistent有無 smallint NOT NULL DEFAULT (-1),
    stenttypeコード smallint NOT NULL DEFAULT (-1),
    永久ペースメーカー使用有無 smallint NOT NULL DEFAULT (-1),
    icd使用有無 smallint NOT NULL DEFAULT (-1),
    急性心筋梗塞有無 smallint NOT NULL DEFAULT (-1),
    急性心筋梗塞のtype smallint NOT NULL,
    急性心筋梗塞_発現日_年 smallint,
    急性心筋梗塞_発現日_月 smallint,
    急性心筋梗塞_発現日_日 smallint,
    心不全症状_最近2週間有無 smallint NOT NULL DEFAULT (-1),
    classificationnyhaコード smallint NOT NULL DEFAULT (-1),
    狭心症有無 smallint NOT NULL DEFAULT (-1),
    狭心症のtype smallint NOT NULL DEFAULT (-1),
    陳旧性心筋梗塞有無 smallint NOT NULL DEFAULT (-1),
    陳旧性心筋梗塞_発現日_年 smallint,
    陳旧性心筋梗塞_発現日_月 smallint,
    陳旧性心筋梗塞_発現日_日 smallint,
    心原性ショック_直前有無 smallint NOT NULL DEFAULT (-1),
    心蘇生の既往有無 smallint NOT NULL DEFAULT (-1),
    不整脈の既往有無 smallint NOT NULL DEFAULT (-1),
    不整脈の既往typeフラグ_sustvtorvf boolean NOT NULL DEFAULT false,
    不整脈の既往typeフラグ_cavb boolean NOT NULL DEFAULT false,
    不整脈の既往typeフラグ_aforafl boolean NOT NULL DEFAULT false,
    不整脈の既往typeフラグ_others boolean NOT NULL DEFAULT false,
    不整脈の既往type_others詳細 text,
    af_or_aflの種類コード smallint NOT NULL DEFAULT (-1),
    moderateまたはsevereな肺高血圧症 smallint NOT NULL DEFAULT (-1),
    高度石灰化大動脈有無 smallint NOT NULL DEFAULT (-1),
    心臓血管系その他有無 smallint NOT NULL DEFAULT (-1),
    心臓血管系その他詳細 text,
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    脳障害の既往フラグ_rind boolean NOT NULL DEFAULT false,
    "企業PMS対象症例コード" smallint NOT NULL DEFAULT (-1),
    企業同意書取得コード smallint NOT NULL DEFAULT (-1),
    外科的に留置した大動脈生体弁SAVの種類 smallint NOT NULL DEFAULT (-1),
    ステント付き生体弁の製品種別 smallint NOT NULL DEFAULT (-1),
    ステントレス同種移植ホモグラフトの別 smallint NOT NULL DEFAULT (-1),
    ステントレス生体弁の製品種別 smallint NOT NULL DEFAULT (-1),
    ステント付き生体弁の製品名その他 text,
    ステントレス生体弁の製品名その他 text
)
SERVER tavi_investigation7_server
OPTIONS (table_name '患者背景');
ALTEr FOREIGN TABLE public.調査7患者背景 OWNER TO tavi_db_maker2;

-- 外部テーブル作成14
DROP FOREIGN TABLE IF EXISTS 調査7術中デバイス不具合;
CREATE FOREIGN TABLE 調査7術中デバイス不具合 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    デバイス不具合登録通番 smallint NOT NULL,
    入力承認ステータス smallint NOT NULL DEFAULT 0,
    不具合機器コード smallint NOT NULL DEFAULT (-1),
    tavi弁の不具合内容コード smallint NOT NULL DEFAULT (-1),
    tavi弁の不具合内容その他詳細 text,
    tavi弁の不具合タイミングフラグ_弁留置前 boolean NOT NULL DEFAULT false,
    tavi弁の不具合タイミングフラグ_弁留置中 boolean NOT NULL DEFAULT false,
    tavi弁の不具合タイミングフラグ_弁留置後 boolean NOT NULL DEFAULT false,
    tavi弁の不具合詳細 text,
    tavi弁の不具合関連有害事象有無 smallint NOT NULL DEFAULT (-1),
    tavi弁以外の不具合内容コード smallint NOT NULL DEFAULT (-1),
    tavi弁以外不具合タイミングフラグ_弁留置前 boolean NOT NULL DEFAULT false,
    tavi弁以外不具合タイミングフラグ_弁留置中 boolean NOT NULL DEFAULT false,
    tavi弁以外不具合タイミングフラグ_弁留置後 boolean NOT NULL DEFAULT false,
    前拡張バルーンの不具合詳細コード smallint NOT NULL DEFAULT (-1),
    前拡張バルーンの不具合その他詳細 text,
    後拡張バルーンの不具合詳細コード smallint NOT NULL DEFAULT (-1),
    後拡張バルーンの不具合その他詳細 text,
    デリバリーシステムの不具合詳細コード smallint NOT NULL DEFAULT (-1),
    デリバリーシステムの不具合その他詳細 text,
    バルーンカテーテルの不良詳細コード smallint NOT NULL DEFAULT (-1),
    バルーンカテーテルの不良その他詳細 text,
    その他の不具合コード smallint NOT NULL DEFAULT (-1),
    その他の不具合詳細 text,
    tavi弁以外の不具合詳細 text,
    tavi弁以外の不具合関連有害事象有無 smallint NOT NULL DEFAULT (-1),
    デバイス不具合関連有害事象レコードid integer,
    登録取消フラグ boolean NOT NULL DEFAULT false,
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text
)
SERVER tavi_investigation7_server
OPTIONS (table_name '術中デバイス不具合');
ALTER FOREIGN TABLE public.調査7術中デバイス不具合 OWNER TO tavi_db_maker2;

-- 外部テーブル作成15
DROP FOREIGN TABLE IF EXISTS 調査7術中情報;
CREATE FOREIGN TABLE 調査7術中情報 (
  id serial NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    術者氏名 character varying(120),
    助手氏名1 character varying(120),
    助手氏名2 character varying(120),
    手術日_年 smallint,
    手術日_月 smallint,
    手術日_日 smallint,
    手術時間_時 smallint,
    手術時間_分 smallint,
    緊急度コード smallint NOT NULL DEFAULT (-1),
    手技の適応コード smallint NOT NULL DEFAULT (-1),
    tavi選択理由フラグ_highrisk boolean NOT NULL DEFAULT false,
    tavi選択理由フラグ_inope boolean NOT NULL DEFAULT false,
    tavi選択理由フラグ_prorisk1 boolean NOT NULL DEFAULT false,
    tavi選択理由フラグ_prorisk2 boolean NOT NULL DEFAULT false,
    tavi選択理由フラグ_patient boolean NOT NULL DEFAULT false,
    tavi選択理由フラグ_other boolean NOT NULL DEFAULT false,
    valveinvalveコード smallint NOT NULL DEFAULT (-1),
    手技中止有無 smallint NOT NULL DEFAULT (-1),
    手技中止の理由コード smallint NOT NULL DEFAULT (-1),
    手技中止の理由その他詳細 text,
    開胸術への移行有無 smallint NOT NULL DEFAULT (-1),
    開胸術への移行の理由コード smallint NOT NULL DEFAULT (-1),
    開胸術への移行の理由その他詳細 text,
    麻酔の種類コード smallint NOT NULL DEFAULT (-1),
    rapidventricularpacing有無 smallint NOT NULL DEFAULT (-1),
    rapidventricularpacing値 numeric(3,1),
    アクセス方法コード smallint NOT NULL DEFAULT (-1),
    アクセス部位コード smallint NOT NULL DEFAULT (-1),
    アクセス部位その他詳細 text,
    アクセス最小血管径 numeric(4,1),
    造影剤量 smallint,
    透視時間未測定フラグ boolean NOT NULL DEFAULT false,
    透視時間 smallint,
    補助循環装置有無 smallint NOT NULL DEFAULT (-1),
    補助循環装置の詳細コード smallint NOT NULL DEFAULT (-1),
    人工心肺の使用有無 smallint NOT NULL DEFAULT (-1),
    人工心肺の使用_緊急度コード smallint NOT NULL DEFAULT (-1),
    人工心肺時間 smallint,
    術中投与薬フラグ_ヘパリン smallint NOT NULL DEFAULT (-1),
    術中投与薬フラグ_アルガトロバン smallint NOT NULL DEFAULT (-1),
    術中投与薬フラグ_カテコラミン smallint NOT NULL DEFAULT (-1),
    術中投与薬フラグ_その他 smallint NOT NULL DEFAULT (-1),
    その他抗凝固薬_抗血小板薬品名 text,
    製品_マルチパック smallint NOT NULL DEFAULT (-1),
    製品_tavi弁 smallint NOT NULL DEFAULT (-1),
    製品_デリバリーシステム smallint NOT NULL DEFAULT (-1),
    製品_イントロデユーサーシースセット smallint NOT NULL DEFAULT (-1),
    製品_バルーンカテーテル smallint NOT NULL DEFAULT (-1),
    製品_後拡張用バルーンカテーテル smallint NOT NULL DEFAULT (-1),
    製品_その他_品名モデル番号 text,
    デバイスの不具合有無 smallint NOT NULL DEFAULT (-1),
    有害事象の有無 smallint NOT NULL DEFAULT (-1),
    登録者id character varying(20),
    登録日時 timestamp without time zone,
    最終更新者id character varying(20),
    最終更新日時 timestamp without time zone,
    削除番号 integer DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    助手氏名3 character varying(120),
    助手氏名4 character varying(120),
    助手氏名5 character varying(120),
    助手氏名6 character varying(120),
    助手氏名7 character varying(120),
    助手氏名8 character varying(120),
    助手氏名9 character varying(120),
    助手氏名10 character varying(120),
    アクセス方法その他詳細 text,
    tavi弁のシリアル番号 character varying(128),
    tavi弁の再収納有無 smallint NOT NULL DEFAULT (-1),
    tavi弁の再収納回数 smallint,
    製品_後拡張用バルーンカテーテル_製品名 text,
    製品_後拡張用バルーンカテーテル_サイズ smallint
)
SERVER tavi_investigation7_server
OPTIONS (table_name '術中情報');
ALTER FOREIGN TABLE public.調査7術中情報 OWNER TO tavi_db_maker2;

-- 外部テーブル作成16
DROP FOREIGN TABLE IF EXISTS 調査7術中有害事象;
CREATE FOREIGN TABLE 調査7術中有害事象 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    有害事象登録通番 smallint NOT NULL,
    確認日_年 smallint,
    確認日_月 smallint,
    確認日_日 smallint,
    発現日_発生日_年 smallint,
    発現日_発生日_月 smallint,
    発現日_発生日_日 smallint,
    デバイスとの因果関係コード smallint NOT NULL DEFAULT (-1),
    手技との因果関係コード smallint NOT NULL DEFAULT (-1),
    重篤度コード smallint NOT NULL DEFAULT (-1),
    重篤と判断した理由コード smallint NOT NULL DEFAULT (-1),
    転帰コード smallint NOT NULL DEFAULT (-1),
    転帰その他詳細 text,
    転帰日_年 smallint,
    転帰日_月 smallint,
    転帰日_日 smallint,
    コメント text,
    デバイス関連有害事象有無 smallint NOT NULL DEFAULT (-1),
    出血関連有害事象有無 smallint NOT NULL DEFAULT (-1),
    循環器関連有害事象有無 smallint NOT NULL DEFAULT (-1),
    入院を要したその他有害事象有無 smallint NOT NULL DEFAULT (-1),
    有害事象カテゴリー smallint NOT NULL DEFAULT (-1),
    有害事象内容コード smallint NOT NULL DEFAULT (-1),
    入力された有害事象名 text,
    登録取消フラグ boolean NOT NULL DEFAULT false,
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT (-1),
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    入力承認ステータス smallint NOT NULL DEFAULT 0,
    有害事象名_デバイス関連その他 text,
    有害事象名_出血関連その他 text,
    有害事象名_入院_循環器系疾患 text,
    有害事象名_入院_消化器系疾患 text,
    有害事象名_入院_呼吸器系疾患 text,
    有害事象名_入院_神経系疾患 text,
    有害事象名_入院_その他腎臓系疾患 text,
    有害事象名_入院_感染性疾患 text,
    有害事象名_入院_その他 text
)
SERVER tavi_investigation7_server
OPTIONS (table_name '術中有害事象');
ALTER FOREIGN TABLE public.調査7術中有害事象 OWNER TO tavi_db_maker2;

-- 外部テーブル作成17
DROP FOREIGN TABLE IF EXISTS 調査7術前情報;
CREATE FOREIGN TABLE 調査7術前情報 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    リスク_測定日_年 smallint,
    リスク_測定日_月 smallint,
    リスク_測定日_日 smallint,
    stsリスクスコア未実施フラグ boolean NOT NULL DEFAULT false,
    stsリスクスコア numeric(4,1),
    euroscore2未実施フラグ boolean NOT NULL DEFAULT false,
    euroscore2 numeric(4,1),
    logistic_euroscore未実施フラグ boolean NOT NULL DEFAULT false,
    logistic_euroscore numeric(4,1),
    ヘモグロビン未測定フラグ boolean NOT NULL DEFAULT false,
    ヘモグロビン値 numeric(3,1),
    ヘモグロビン_測定日_年 smallint,
    ヘモグロビン_測定日_月 smallint,
    ヘモグロビン_測定日_日 smallint,
    血小板数未測定フラグ boolean NOT NULL DEFAULT false,
    血小板数値 numeric(4,1),
    クレアチニン値未測定フラグ boolean NOT NULL DEFAULT false,
    クレアチニン値 numeric(3,1),
    クレアチニン_測定日_年 smallint,
    クレアチニン_測定日_月 smallint,
    クレアチニン_測定日_日 smallint,
    inr未測定フラグ boolean NOT NULL DEFAULT false,
    inr値 numeric(3,1),
    aptt測定状況フラグ boolean NOT NULL DEFAULT false,
    aptt値 numeric(4,1),
    トータルビリルビン_測定状況フラグ boolean NOT NULL DEFAULT false,
    トータルビリルビン numeric(3,1),
    アルブミン未測定フラグ boolean NOT NULL DEFAULT false,
    アルブミン値 numeric(3,1),
    十二誘導心電図有無 smallint NOT NULL DEFAULT (-1),
    十二誘導心電図_実施日_年 smallint,
    十二誘導心電図_実施日_月 smallint,
    十二誘導心電図_実施日_日 smallint,
    十二誘導心電図_異常所見有無 smallint NOT NULL DEFAULT (-1),
    十二心電_異常所見フラグ_完全右脚ブロック boolean NOT NULL DEFAULT false,
    十二心電_異常所見フラグ_完全左脚ブロック boolean NOT NULL DEFAULT false,
    十二心電_異常所見フラグ_洞不全症候群 boolean NOT NULL DEFAULT false,
    十二心電_異常所見フラグ_房室ブロック boolean NOT NULL DEFAULT false,
    十二心電_異常所見フラグ_その他 boolean NOT NULL DEFAULT false,
    十二心電_異常所見フラグ_その他内容 text NOT NULL,
    preopcath有無 smallint NOT NULL DEFAULT (-1),
    術前心カテ_実施日_年 smallint,
    術前心カテ_実施日_月 smallint,
    術前心カテ_実施日_日 smallint,
    狭窄度_左主幹部 smallint NOT NULL DEFAULT (-1),
    狭窄度_左前下行枝_近位部 smallint NOT NULL DEFAULT (-1),
    狭窄度_左前下行枝_遠位部_対角枝 smallint NOT NULL DEFAULT (-1),
    狭窄度_左回旋枝_鈍緑枝 smallint NOT NULL DEFAULT (-1),
    狭窄度_右冠動脈 smallint NOT NULL DEFAULT (-1),
    lv_function smallint NOT NULL DEFAULT (-1),
    術前心エコー有無 smallint NOT NULL DEFAULT (-1),
    術前心エコ_実施日_年 smallint,
    術前心エコ_実施日_月 smallint,
    術前心エコ_実施日_日 smallint,
    lvef値 smallint,
    leftatrialdimension未測定フラグ boolean NOT NULL DEFAULT false,
    leftatrialdimension値 numeric(4,1),
    ldesd_lvedd未測定フラグ boolean NOT NULL DEFAULT false,
    ldesd_lvedd値 numeric(3,1),
    septalwallthickness未測定フラグ boolean NOT NULL DEFAULT false,
    septalwallthickness値 numeric(4,1),
    posteriorwallthickness未測定フラグ boolean NOT NULL DEFAULT false,
    posteriorwallthickness値 numeric(4,1),
    大動脈弁異常の有無 smallint NOT NULL DEFAULT (-1),
    大動脈弁異常フラグ_degenerative boolean NOT NULL DEFAULT false,
    大動脈弁異常フラグ_endocarditis boolean NOT NULL DEFAULT false,
    大動脈弁異常フラグ_congenital boolean NOT NULL DEFAULT false,
    大動脈弁異常フラグ_rheumatic boolean NOT NULL DEFAULT false,
    大動脈弁異常フラグ_primary_aotic boolean NOT NULL DEFAULT false,
    大動脈弁異常フラグ_lv_outflow boolean NOT NULL DEFAULT false,
    大動脈弁異常フラグ_supravalvular boolean NOT NULL DEFAULT false,
    大動脈弁異常フラグ_tumor boolean NOT NULL DEFAULT false,
    大動脈弁異常フラグ_trauma_or_surgical boolean NOT NULL DEFAULT false,
    大動脈弁異常フラグ_other boolean NOT NULL DEFAULT false,
    大動脈弁の形態コード smallint NOT NULL DEFAULT (-1),
    大動脈弁の形態_それ以外内容 text,
    大動脈弁輪石灰化有無 smallint NOT NULL DEFAULT (-1),
    大動脈弁疾患の要因コード smallint NOT NULL DEFAULT (-1),
    大動脈弁疾患の要因_その他詳細 text,
    大動脈弁ピーク時の血流速 numeric(4,1),
    大動脈弁輪サイズ測定コード smallint NOT NULL DEFAULT (-1),
    大動脈弁輪サイズ numeric(3,1),
    大動脈弁狭窄有無 smallint NOT NULL DEFAULT (-1),
    平均圧較差 numeric(4,1),
    peakaorticvalvegradient numeric(4,1),
    大動脈弁口面積 numeric(2,1),
    大動脈弁逆流コード smallint NOT NULL DEFAULT (-1),
    逆流の箇所コード smallint NOT NULL DEFAULT (-1),
    mitalinsufficiencyコード smallint NOT NULL DEFAULT (-1),
    mitralstenosis smallint NOT NULL DEFAULT (-1),
    tricuspidinsufficiencyコード smallint NOT NULL DEFAULT (-1),
    術前投薬ヘパリン有無 smallint NOT NULL DEFAULT (-1),
    術前投薬ワーファリン有無 smallint NOT NULL DEFAULT (-1),
    トロンビン_xa阻害薬 smallint NOT NULL DEFAULT (-1),
    術前投薬アスピリン有無 smallint NOT NULL DEFAULT (-1),
    クロピドグレル_プラスグレル smallint NOT NULL DEFAULT (-1),
    術前投薬チクロピジン有無 smallint NOT NULL DEFAULT (-1),
    その他の抗凝固薬_抗血小板薬フラグ smallint NOT NULL DEFAULT (-1),
    その他の抗凝固薬_抗血小板薬品名 text,
    術前投薬カテコラミン有無 smallint NOT NULL DEFAULT (-1),
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    lvesd未測定フラグ boolean NOT NULL DEFAULT false,
    lvesd値 numeric(3,1),
    lvedd未測定フラグ boolean NOT NULL DEFAULT false,
    lvedd値 numeric(3,1),
    術前ct有無 smallint NOT NULL DEFAULT (-1),
    大動脈弁弁輪サイズ_面積_ct numeric(4,2),
    大動脈弁弁輪サイズ_面積_ct未測定フラグ boolean NOT NULL DEFAULT false,
    大動脈弁弁輪サイズ_弁周囲径_ct numeric(4,1),
    大動脈弁弁輪サイズ_弁周囲径_ct未測定フラグ boolean NOT NULL DEFAULT false,
    clinicalFrailtyScale smallint
)
SERVER tavi_investigation7_server
OPTIONS (table_name '術前情報');
ALTER FOREIGN TABLE public.調査7術前情報 OWNER TO tavi_db_maker2;

-- 外部テーブル作成18
DROP FOREIGN TABLE IF EXISTS 調査7術後情報;
CREATE FOREIGN TABLE 調査7術後情報 (
    id integer NOT NULL,
    tavi症例データ管理レコードid integer NOT NULL,
    術後最低hemoglobin未測定フラグ boolean NOT NULL DEFAULT false,
    術後最低hemoglobin numeric(3,1),
    術後最高クレアチニン未測定フラグ boolean NOT NULL DEFAULT false,
    術後最高クレアチニン値 numeric(3,1),
    術後最高tnt未測定フラグ boolean NOT NULL DEFAULT false,
    術後最高tnt numeric(4,3),
    術後最高ck未測定フラグ boolean NOT NULL DEFAULT false,
    術後最高ck numeric(4,0),
    血管へのアクセス等成功有無 smallint NOT NULL DEFAULT (-1),
    tavi弁の適切な留置有無 smallint NOT NULL DEFAULT (-1),
    術後有効弁口面積 numeric(3,2),
    術後平均圧較差 numeric(4,1),
    術後最大流速 numeric(4,1),
    術後大動脈弁逆流コード smallint NOT NULL DEFAULT (-1),
    逆流の箇所コード smallint NOT NULL DEFAULT (-1),
    tavi弁の追加留置有無 smallint NOT NULL DEFAULT (-1),
    tavi弁の追加留置詳細コード smallint NOT NULL DEFAULT (-1),
    tavi弁の追加留置その他詳細 text,
    登録者id character varying(20) NOT NULL,
    登録日時 timestamp without time zone NOT NULL,
    最終更新者id character varying(20) NOT NULL,
    最終更新日時 timestamp without time zone NOT NULL,
    削除番号 integer NOT NULL DEFAULT 0,
    システム制御用1 text,
    システム制御用2 text,
    システム制御用3 text,
    術後有効弁口面積未測定フラグ boolean NOT NULL DEFAULT false,
    術後平均圧較差未測定フラグ boolean NOT NULL DEFAULT false,
    術後最大流速未測定フラグ boolean NOT NULL DEFAULT false
)
SERVER tavi_investigation7_server
OPTIONS (table_name '術後情報');
ALTER FOREIGN TABLE public.調査7術後情報 OWNER TO tavi_db_maker2;


-- ------------------------------------------------------------------------------------------
-- 調査7のView表作成
-- ------------------------------------------------------------------------------------------
CREATE VIEW public.調査7調査対象症例_view AS
 SELECT tavi症例データサマリ.tavi症例データ管理レコードid,
    tavi症例データサマリ.手術日,
    0 AS 施設診療科マスタレコードid,
    0 AS 施設調査契約マスタレコードid,
    50000 AS 契約件数,
    0 AS rank
   FROM public.tavi症例データサマリ
  WHERE tavi症例データサマリ.調査対象フラグ = true;


ALTER TABLE 調査6調査対象症例_view OWNER TO tavi_db_maker2;
